version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.12

    working_directory: ~/phoenixtw.github.io

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Deploy website
          command: npm run deploy
