version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/node:12.12

    working_directory: ~/phoenixtw.github.io

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Deploy website
          command: |
            if echo "${CIRCLE_BRANCH}" | grep -Eq "develop"; then
              REPOSITORY="https://phoenixcibot:${GITHUB_TOKEN}@github.com/phoenixTW/phoenixtw.github.io.git"
              git config user.email phoenixcibot@users.noreply.github.com
              git config user.name phoenixcibot
              git remote set-url origin ${REPOSITORY}
              npm run deploy
            else
              echo "No website released."
            fi
